name: Terraform Plan and Apply

on:
  pull_request:
    types: [opened, synchronize, reopened]
  push:
    branches:
      - main

jobs:
  terraform-plan:
    if: github.event_name == 'pull_request'
    name: Terraform Plan
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: infra

    steps:
      - uses: actions/checkout@v3

      - uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.5.7

      - uses: aws-actions/configure-aws-credentials@v3
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - run: terraform init
      - run: terraform validate

      - name: Terraform Plan
        run: terraform plan -no-color

  terraform-apply:
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    name: Terraform Apply
    runs-on: ubuntu-latest
    needs: terraform-plan

    defaults:
      run:
        working-directory: infra

    steps:
      - uses: actions/checkout@v3

      - uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.5.7

      - uses: aws-actions/configure-aws-credentials@v3
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - run: terraform init
      - run: terraform apply -auto-approve


